### ISSUE TITLE
Doesn't work correctly with iterator methods

### ISSUE THREAD

**Issue by WalkerCodeRanger** [Fody/ExtraConstraints#10]
It appears that miking the enum constraint (and I would assume the delegate constraint) with C# iterator methods doesn't work.  Here is a unit test that reproduces the issue:

```
public enum MyEnum
{
    None = 0,
    Value = 1,
}

public class MyClass<[EnumConstraint] T> where T : struct
{
}

public class MyFactory<[EnumConstraint] T> where T : struct
{
    public IEnumerable<MyClass<T>> Create()
    {
        yield return new MyClass<T>();
    }
}

[TestFixture]
public class ExtraConstraintsTests
{
    [Test]
    public void MyTest()
    {
        var factory = new MyFactory<MyEnum>();
        var enumerable = factory.Create();
    }
}
```

This gives a runtime error of: "System.TypeLoadException : GenericArguments[0], 'T', on 'MyClass`1[T]' violates the constraint of type parameter 'T'." on the call to`factory.Create()`. (note, the behavior is somewhat easier to see if the classes are in a different assembly than the unit test because that delays the type load).

From looking at the disassembly with [ilspy](http://ilspy.net/), I am thinking the problem is that the enum constraint is not applied to the  iterator class that is automatically generated by the compiler.

**Comment by SimonCropp** [comment]
@WalkerCodeRanger TBH i am not sure why this is happening. do you have any ideas?

**Comment by WalkerCodeRanger** [comment]
@SimonCropp the way iterator methods work under the hood is the compiler rewrites them into a generated iterator class which the method returns.  That class holds the state of the method between the the yield steps.  When the original method is generic, then the newly generated class is also generic. The extra constraint is not being applied to the generated class.  Then at runtime the VM is detecting that the applied constraint isn't properly enforced by the generated class. That is like the compiler error you get when calling a generic method with your own type parameter that doesn't have the same generic constraint.

**Comment by SimonCropp** [comment]
@WalkerCodeRanger do you want to have a go at submitting a PR for this?

**Comment by WalkerCodeRanger** [comment]
@SimonCropp sorry, I'm busy with other projects right now.
