### ISSUE TITLE
NugetPackage: .NET 3.5 compatibility

### ISSUE THREAD

**Issue by DoctorVanGogh** [Fody/ExtraConstraints#13]
The current package will not install into a project targeting .NET 3.5.

Fody itself will happily install into those project. Either both ExtraConstraints & Fody should work or neither.

**Comment by SimonCropp** [comment]
Support ended for 3.5 6 years ago. 

I am curious as the the use case u have for still requiring support

**Comment by DoctorVanGogh** [comment]
It's for a managed assembly for a Unity game that [ships](http://answers.unity3d.com/questions/1305565/as-of-12017-what-is-the-highest-version-of-net-tha.html) with a Mono version with a feature set (and binary compatibility) of 3.5 (Well, at least kinda, sorta, in a way).

I'm aware that 3.5 is quite an outdated runtime version, and if the base Fody package wouldn't support 3.5 I wouldn't have asked.

---

Also, _technically_ 3.5 is not necessarily out of support - if you're running 3.5 SP1 it may still be supported: 
> .NET Framework 3.5 SP1 is supported on [...] Windows Server 2012 R2, Windows 10, and Windows Server 2016 according to the end of support date for each operating system.

Source: https://support.microsoft.com/en-us/help/17455/lifecycle-faq-net-framework (﻿What is the Lifecycle Policy for the different versions of the .NET Framework?)

With that we get a maximum end of support of 9/10/2018 (on Server 2012 R2), 13/10/2020 (If running of Windows 10) & 11/01/2022 (for Server 2016).

---

But ultimately I don't wanna nitpick. If _you_ no longer want to support 3.5 that's _your_ decision. If there's a technical reason, why the `ExtraConstraints` package requires 4.0 (or higher) I'll deal with it. If it's just a compilation toggle/publishing issue I'll happily take an updated nuget package 😉

**Comment by SimonCropp** [comment]
sorry for the inconvenience. but i have no interest in going to the extra effort required to support such an old runtime. and no it is not a technical reason. mostly it is that i want to avoid doing support for organisations that cannot keep their tooling+environments reasonable up to date for projects that are being actively worked on
