### ISSUE TITLE
No actual constraintion

### ISSUE THREAD

**Issue by bessgeor** [Fody/ExtraConstraints#14]
See repro 1 at https://github.com/bessgeor/ExtraConstraintsRepro

**Comment by SimonCropp** [comment]
repro doesnt compile

**Comment by bessgeor** [comment]
Repro 2 breaks build (that's the thing of the repro). You could reset repro 2 commit in case to get repro 1

**Comment by SimonCropp** [comment]
you are missing the fodyweavers.xml https://github.com/Fody/ExtraConstraints/#add-to-fodyweaversxml

**Comment by bessgeor** [comment]
I have added the xml but errors are still in place. However, I guess that there should be some project configuration to use Fody but I can't find anything related with exception for some VS add-in which I can't install now.
