### ISSUE TITLE
Add `struct` constraint to `[EnumConstraint]` by default

### ISSUE THREAD

**Issue by mqudsi** [Fody/ExtraConstraints#19]
`Enum` is an ungodly special type and I could go on and on about the deficiencies and shortcomings of its design that would be ridiculously easy to fix in a point update to the language, but I won't.

However, in order to use `Enum.TryParse<T>`, `T` must be non-nullable. The easiest way to get a non-nullable constraint (and it would be fully compatible with `[EnumConstraint]`) is to simply specify an additional `where T: struct` constraint. Since all enums in C# are non-nullable types (aka "structs"), `Foo<[EnumConstraint] T>` should automatically also constrain `T` to `struct` as well.

**Comment by SimonCropp** [comment]
Sounds good. Send us a PR

**Comment by SimonCropp** [comment]
let me know if u ever get to that PR
