### ISSUE TITLE
'ExtraConstraints' does not have a strong name.

### ISSUE THREAD

**Issue by neremin** [Fody/ExtraConstraints#8]
Using 1.10.2.0 version. Get this error during compilation:

error CS1577: Assembly generation failed -- Referenced assembly 'ExtraConstraints' does not have a strong name

Would be lovely to make it work out of the box.

**Comment by SimonCropp** [comment]
Why do u want to use strong naming?

**Comment by neremin** [comment]
Developing for sharepoint. This is a must for farm solutions.

воскресенье, 1 февраля 2015 г. пользователь Simon Cropp написал:

**Comment by SimonCropp** [comment]
on nuget

**Comment by neremin** [comment]
Thanks for the fix. I've installed it and could build the project. But it does not work for me, or I'm doing something wrong.

       public static TEnum ToEnum<[EnumConstraint] TEnum>(this string value)
        {
            return (TEnum) Enum.Parse(typeof (TEnum), value);
        }

I can pass any non-Enum type as generic argument and the project builds. Isn't it supposed to stop the build if constraint is violated?
