### ISSUE TITLE
Build proceeds when constraint is violatied.

### ISSUE THREAD

**Issue by neremin** [Fody/ExtraConstraints#9]
Thanks for the strong name fix. I've installed it and could build the project. But it does not work for me, or I'm doing something wrong. For instance, in this extension method:

       public static TEnum ToEnum<[EnumConstraint] TEnum>(this string value)
        {
            return (TEnum) Enum.Parse(typeof (TEnum), value);
        }

I can pass any non-Enum type as a generic argument and the project builds successfully (namely some class type). Isn't the build supposed to be stopped if constraint is violated?

**Comment by SimonCropp** [comment]
yeah i build this to add extra constraints to a lib so that "from a consuming libraries perspective constrains would be verified". it was not been build to apply those conventions within the current library. 

did you want to have a go at a pull request?

**Comment by neremin** [comment]
I see. Perhaps I will make a pull request one day. Very busy right now.

**Comment by SimonCropp** [comment]
let me know when you get around to that pull request
